FROM openjdk:17-jdk-alpine
VOLUME /tmp
WORKDIR /app
RUN ls -la /target/ || echo "No target directory yet"

COPY target/EbankingPrjt-1.0-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]


