FROM node:18-alpine AS build
WORKDIR /app
COPY ./package*.json ./
RUN npm install
COPY . .
RUN npm run build -- --configuration=production --base-href=/

FROM nginx:alpine
COPY --from=build /app/dist/angular-ui /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
